CREATE SEQUENCE client_seq
START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE TABLE tb_client (
    id NUMBER(19, 0) DEFAULT client_seq.NEXTVAL PRIMARY KEY NOT NULL,
    name VARCHAR2(150) NOT NULL,
    email VARCHAR2(254) NOT NULL,
    phone VARCHAR2(50) NOT NULL
);