CREATE SEQUENCE user_seq
    START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE TABLE tb_user (
    id NUMBER(19, 0) DEFAULT user_seq.NEXTVAL PRIMARY KEY NOT NULL,
    name VARCHAR2(150) NOT NULL,
    email VARCHAR2(254) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    create_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    update_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);